name: surf_study_project
version: "0.0.1-dev.0"
description: a Flutter template project for development.
publish_to: none

dependencies:
  auto_route: 5.0.1
  cached_network_image: 3.2.3
  dio: 4.0.6
  elementary: 1.5.0
  firebase_crashlytics: 3.0.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: 5.6.0
  flutter_svg: 1.1.6
  infinite_scroll_pagination: 3.2.0
  logger: 1.1.0
  provider: 6.0.3
  retrofit: 3.0.1+1
  shared_preferences: 2.0.15
  smooth_page_indicator: 1.0.0+2
  surf_logger: 1.1.0

dev_dependencies:
  auto_route_generator: 5.0.2
  build_runner: 2.2.1
  dart_code_metrics: 4.18.3
  elementary_test: 1.1.2
  flutter_test:
    sdk: flutter
  json_serializable: 6.3.2
  retrofit_generator: 4.0.3+2
  surf_lint_rules: 1.5.0

environment:
  sdk: ">=2.18.5-0 <3.0.0"

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/icons/catalog/
    - assets/icons/icon/
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic